-- Esquema apexstore_tx. Compatible con PostgreSQL y con H2 en modo PostgreSQL.
-- Los datos del medio de pago (tokens, cuentas, wallets) no se guardan.

CREATE TABLE IF NOT EXISTS transaccion (
    id_orden     VARCHAR(64)  PRIMARY KEY,
    cliente_id   VARCHAR(64)  NOT NULL,
    medio        VARCHAR(32)  NOT NULL,
    monto        BIGINT       NOT NULL CHECK (monto > 0),
    moneda       VARCHAR(8)   NOT NULL,
    estado       VARCHAR(16)  NOT NULL,
    codigo       VARCHAR(64),
    mensaje      VARCHAR(255),
    creada       TIMESTAMP    NOT NULL,
    actualizada  TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS auditoria (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden         VARCHAR(64)  NOT NULL REFERENCES transaccion (id_orden),
    estado_anterior  VARCHAR(16),
    estado_nuevo     VARCHAR(16)  NOT NULL,
    detalle          VARCHAR(255),
    fecha            TIMESTAMP    NOT NULL
);
